// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MedicallexiconProject.Controllers {
    public partial class AdministratorController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdministratorController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdministratorController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdministratorController Actions { get { return MVC.Administrator; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Administrator";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Administrator";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string WordAdmin = "WordAdmin";
            public readonly string CategoryAdmin = "CategoryAdmin";
            public readonly string LanguageAdmin = "LanguageAdmin";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Index = "Index";
            public const string WordAdmin = "WordAdmin";
            public const string CategoryAdmin = "CategoryAdmin";
            public const string LanguageAdmin = "LanguageAdmin";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string CategoryAdmin = "~/Views/Administrator/CategoryAdmin.cshtml";
            public readonly string Index = "~/Views/Administrator/Index.cshtml";
            public readonly string LanguageAdmin = "~/Views/Administrator/LanguageAdmin.cshtml";
            public readonly string WordAdmin = "~/Views/Administrator/WordAdmin.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AdministratorController: MedicallexiconProject.Controllers.AdministratorController {
        public T4MVC_AdministratorController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult WordAdmin() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.WordAdmin);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CategoryAdmin() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CategoryAdmin);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LanguageAdmin() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LanguageAdmin);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
