// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MedicallexiconProject.Controllers {
    public partial class WordController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected WordController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Index() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult UploadWordsPicture() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.UploadWordsPicture);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Details() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Delete() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult WordInfo() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.WordInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Search() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Search);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult QuickSearch() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.QuickSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CheckWord() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.CheckWord);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public WordController Actions { get { return MVC.Word; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Word";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Word";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Create = "Create";
            public readonly string UploadWordsPicture = "UploadWordsPicture";
            public readonly string Details = "Details";
            public readonly string Delete = "Delete";
            public readonly string Edit = "Edit";
            public readonly string WordInfo = "WordInfo";
            public readonly string Search = "Search";
            public readonly string QuickSearch = "QuickSearch";
            public readonly string CheckWord = "CheckWord";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Index = "Index";
            public const string Create = "Create";
            public const string UploadWordsPicture = "UploadWordsPicture";
            public const string Details = "Details";
            public const string Delete = "Delete";
            public const string Edit = "Edit";
            public const string WordInfo = "WordInfo";
            public const string Search = "Search";
            public const string QuickSearch = "QuickSearch";
            public const string CheckWord = "CheckWord";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index {
            public readonly string sort = "sort";
            public readonly string sortdir = "sortdir";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_UploadWordsPicture s_params_UploadWordsPicture = new ActionParamsClass_UploadWordsPicture();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadWordsPicture UploadWordsPictureParams { get { return s_params_UploadWordsPicture; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadWordsPicture {
            public readonly string file = "file";
        }
        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_WordInfo s_params_WordInfo = new ActionParamsClass_WordInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WordInfo WordInfoParams { get { return s_params_WordInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WordInfo {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search {
            public readonly string query = "query";
        }
        static readonly ActionParamsClass_QuickSearch s_params_QuickSearch = new ActionParamsClass_QuickSearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QuickSearch QuickSearchParams { get { return s_params_QuickSearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QuickSearch {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_CheckWord s_params_CheckWord = new ActionParamsClass_CheckWord();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckWord CheckWordParams { get { return s_params_CheckWord; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckWord {
            public readonly string name = "name";
            public readonly string selectedLanguageID = "selectedLanguageID";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _WordInfo = "~/Views/Word/_WordInfo.cshtml";
            public readonly string _WordList = "~/Views/Word/_WordList.cshtml";
            public readonly string _WordSearch = "~/Views/Word/_WordSearch.cshtml";
            public readonly string Create = "~/Views/Word/Create.cshtml";
            public readonly string Details = "~/Views/Word/Details.cshtml";
            public readonly string Index = "~/Views/Word/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_WordController: MedicallexiconProject.Controllers.WordController {
        public T4MVC_WordController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(string sort, string sortdir, int? page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            callInfo.RouteValueDictionary.Add("sort", sort);
            callInfo.RouteValueDictionary.Add("sortdir", sortdir);
            callInfo.RouteValueDictionary.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create(MedicallexiconProject.ViewModel.WordViewModel wordViewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            callInfo.RouteValueDictionary.Add("wordViewModel", wordViewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UploadWordsPicture(System.Web.HttpPostedFileBase file) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UploadWordsPicture);
            callInfo.RouteValueDictionary.Add("file", file);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Details(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Details);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Delete(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult WordInfo(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.WordInfo);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Search(string query) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Search);
            callInfo.RouteValueDictionary.Add("query", query);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult QuickSearch(string term) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.QuickSearch);
            callInfo.RouteValueDictionary.Add("term", term);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CheckWord(string name, int selectedLanguageID) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CheckWord);
            callInfo.RouteValueDictionary.Add("name", name);
            callInfo.RouteValueDictionary.Add("selectedLanguageID", selectedLanguageID);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
